use_frameworks!

target 'SKLogDebugger_Example' do
  pod 'SKLogDebugger', :path => '../'
end

post_install do | installer |
    
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '5.0'
        end
    end
    
    installer.pods_project.build_configurations.each do |config|
        config.build_settings['CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED'] = 'YES'
    end
    installer.pods_project.root_object.known_regions = ["Base", "en"]
    installer.pods_project.root_object.development_region = "en"
    
end
